spring:
  # MYSQL数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/{{ProjectName|lowercase}}_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&serverTimezone=GMT%2B8
    username: {{ProjectName|lowercase}}-user
    password: {{Seed|randomPassword}}
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日志配置
logging:
  level:
    {{Package}}: INFO

default:
  security:
    jwt:
      secret:  {{Seed|randomSecret}}  #不同的profile使用不同的secret
  # 项目中自定义配置的属性请放在此处  