spring:
  # MYSQL数据库配置
  datasource:
    url: jdbc:h2:file:~/{{ProjectName}}
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

# 日志配置
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    {{Package}}: DEBUG

default:
  security:
    jwt:
      secret:  "this is test environment secret" #不同的profile使用不同的secret
  # 项目中自定义配置的属性请放在此处
